### ISSUE TITLE
Just have a question about `/json/list` interface.

### ISSUE THREAD

**Issue by JimmyLv** [panzhangwang/getAwesomeness#23]
Why did you expose this url? I could not see where you used it.

Thanks! :D

**Comment by panzhangwang** [comment]
It is there for typeahead, check main.js

**Comment by JimmyLv** [comment]
谢谢您的回复，还有一个问题就是怎么把Markdown源文件直接渲染成HTML的呀？我在模板里面找到

```
<article class="markdown-body">
            {{ md(article) }}
        </article>
```

但具体的`md()`函数写在哪里呢？谢谢！

**Comment by panzhangwang** [comment]
see it in /lib/uihelpers.js

**Comment by JimmyLv** [comment]
@panzhangwang Awesome! Thank you very much!
