### ISSUE TITLE
wrong padding on `.list-group`

### ISSUE THREAD

**Issue by sobolevn** [panzhangwang/getAwesomeness#24]
There's an issue on the latest Chrome, Mac.

It was:
![2015-12-03 15 38 43](https://cloud.githubusercontent.com/assets/4660275/11560815/3e765640-99d4-11e5-9943-0b2f8db77922.png)

After fix:
![2015-12-03 15 38 33](https://cloud.githubusercontent.com/assets/4660275/11560816/3e77a874-99d4-11e5-9d1f-a7c3034a9cde.png)

CSS to fix:

    .list-group h4:last-child {
        padding-bottom: 10px; }

I can submit a PR.

**Comment by panzhangwang** [comment]
Thanks. Hope to see your PR.
