### ISSUE TITLE
similar project called awesome search and up-to-date awesome list.

### ISSUE THREAD

**Issue by lockys** [panzhangwang/getAwesomeness#26]
We just started a project called `awesome search` about retrieving awesome list a month ago.
And someone told me you have done the similar project already after we started.
It's a great work! but it seems that the awesome list grows rapidly.

We parse the latest markdown of awesome list into JSON format.(But it's different structure..)
https://github.com/lockys/awesome.json/blob/master/awesome/awesome.json
Maybe you could take a look at it :)

Also, this is our project site for now.
https://github.com/lockys/awesome-search

**Comment by panzhangwang** [comment]
Good to know. I like the idea of JSON parsing and searching.
